### ISSUE TITLE
doc: broken layout when there are long lines in code blocks/demos.

### ISSUE THREAD

**Issue by cpylua** [youzan/zent#227]
Add

```scss
.side-nav {
  flex-shrink: 0;
}

.page-content {
  overflow-x: scroll
}
```
