### ISSUE TITLE
Table 中 flex 和 content-box 结合会导致宽度不正确。

### ISSUE THREAD

**Issue by LucasIcarus** [youzan/zent#390]
Table 组件的默认样式中使用 padding 做了居中，但是很多项目默认的 base-css 里没有
```css
* {
  box-sizing: border-box;
}
```
这导致使用 content-box 时其实每一个 cell 占据的页面宽度和设置值不符，当试图去做单行文字 ellipsis 时会，因为 `flex-shrink: 1` 导致对齐出错。

考虑是否可以在 Table 的样式中添加 `div { box-sizing: border-box; }`?

另：考虑添加一个Table cell 中文字 ellipsis 时自动添加 Pop 提示完整内容的功能以支撑业务。
